# -*- coding: utf-8 -*-
"""Math  AI SA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r-69FyWlb7EGnpFYG-afI-iSYhuXSLxF
"""

import pandas as pd

# Load dataset (already uploaded)
df = pd.read_csv("/content/space_missions_dataset.csv")

# --- Step 1: Convert Launch Date to datetime ---
df['Launch Date'] = pd.to_datetime(df['Launch Date'], errors='coerce')

# Print columns to debug KeyError
print("DataFrame Columns:", df.columns)

# --- Step 2: Convert numeric columns ---
numeric_cols = ['Mission Cost (billion USD)', 'Payload Weight (tons)', 'Fuel Consumption (tons)',
                'Mission Duration (years)', 'Distance from Earth (light-years)', 'Crew Size']
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# --- Step 3: Handle missing values ---
# Fill numeric columns with median
for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

# Fill categorical columns with "Unknown"
categorical_cols = ['Mission Type', 'Launch Vehicle', 'Mission Success (%)']
for col in categorical_cols:
    df[col] = df[col].fillna("Unknown")

# --- Step 4: Remove duplicates and invalid entries ---
df.drop_duplicates(inplace=True)
df = df[df['Payload Weight (tons)'] >= 0]
df = df[df['Fuel Consumption (tons)'] >= 0]

# --- Step 5: Standardize categorical values ---
df['Mission Success (%)'] = df['Mission Success (%)'].astype(str).str.strip().str.lower()

# --- Step 6: Verify cleaned data ---
print(df.info())
print(df.describe(include='all'))